version: '3'
services:
  nginx:
    image: nginx:1.17.10-alpine
    restart: always
    # 端口映射
    ports:
      - "8080:80"
    # 数据卷
    volumes:
      # 映射主机./nginx/conf.d目录到容器/etc/nginx/conf.d目录
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/www:/usr/share/nginx/html"
    # 容器名称
    container_name: "nginx"
